
Vagrant.configure("2") do |config|

  config.vm.define "sandbox" do |sandbox|
    sandbox.vm.box = "bento/ubuntu-22.04"
    sandbox.vm.hostname = "sandbox.local"
    sandbox.vm.network "private_network", ip: "172.16.48.131"
    
    sandbox.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end