# Vagrant.configure("2") do |config|
#   config.vm.box = "generic/ubuntu2204"
#   config.vm.provider "qemu" do |qe|
#     qe.arch = "x86_64"
#     qe.machine = "q35"
#     qe.cpu = "max"
#     qe.net_device = "virtio-net-pci"
#     qe.ssh_port = "50023"
#   end
# end

# Vagrant.configure("2") do |config| 
#   config.vm.box = "" # choose a box type for your requirement
#   config.vm.box_version = ""  # specify box version
#   config.vm.box_check_update = false
#   config.vm.provider "generic/ubuntu2204" do |vmware|
#   vmware.gui = false
#   vmware.allowlist_verified = true
# end
# end

# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-22.04"

#   config.vm.provider "vmware_desktop" do |v|
#     v.name = "sandbox"
#     v.memory = 2048
#     v.cpus = 2
#   end
# end

Vagrant.configure("2") do |config|
  config.vm.define "sandbox" do |sandbox|
    sandbox.vm.box = "bento/ubuntu-22.04"
    sandbox.vm.hostname = "sandbox.local"

    sandbox.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end