---
- name: Basic installation for deployment
  hosts: app
  become: true
  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: yes
    - name: Install firewalld
      apt:
        name: firewalld
        state: present
    - name: Ensure firewalld is stopped (testing)
      service:
        name: firewalld
        state: stopped
    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present
    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present
    - name: Install Forever through npm
      npm:
        name: forever
        global: true
        state: present
    - name: Ensure Nodejs app folder exists
      file:
        path: "{{ node_apps_location }}"
        state: directory
    # ! use 'synchronize' of 'rsync' for big group of files !
    - name : Copy file to the app folder
      copy:
        src: "app"
        dest: "{{node_apps_location}}"
    - name: Install app dependencies
      npm:
        path: "{{ node_apps_location }}/app"
    - name: Check list of running apps
      command: "/usr/local/bin/forever list"
      register: forever_list
      changed_when: false
    - name: Run app with Forever
      command: "/usr/local/bin/forever start {{node_apps_location}}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location+'/app/app.js') == -1"
        

        


